version: '2.1'

services:
  helpy:
    image: mikelkew/helpy
    restart: always
    networks:
      - web
      - default
    volumes:
      - rails-assets:/helpy/public
    env_file: docker/.env
    environment:
      - UNICORN_PORT=9000
    #  - DO_NOT_PREPARE=true
    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - "9000"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:support.roaradventures.com"
      - "traefik.port=9000"
  postgres:
    image: postgres:9.4
    restart: always
    networks:
      - default
    env_file: docker/.env
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  rails-assets:
    driver: local

networks:
  web:
    external: true
