version: '2.1'

services:
  caddy:
    image: webwurst/caddy
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/caddy/certs
    volumes_from:
      - helpy:ro
    networks:
      - proxy
      - front
    restart: always
    labels:
      - "traefik.backend=caddy"
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:support.roaradventures.com"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.port=80"
    depends_on:
      - helpy
  helpy:
    image: mikelkew/helpy:traefik
    restart: always
    networks:
      - front
      - back
    volumes:
      - rails-assets:/helpy/public
    env_file: docker/.env
    environment:
      - UNICORN_PORT=8080
    #  - DO_NOT_PREPARE=true
    depends_on:
      - postgres
    expose:
      - "8080"
    labels:
      - "traefik.enable=false"
  postgres:
    image: postgres:9.4
    restart: always
    networks:
      - back
    ports:
      - 5432:5432
    env_file: docker/.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"

volumes:
  rails-assets:
    driver: local

networks:
  proxy:
    external: true
  front:
    driver: bridge
  back:
    driver: bridge
