default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  port: 5432
  host: localhost

development:
  <<: *default
  database: helpy_development

test:
  <<: *default
  database: helpy_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'helpy_production' %>
  username: <%= ENV['POSTGRES_USER'] || 'helpy' %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] || localhost %>
